# Exception Handling

[Zurück](../../Readme.md)

---

An zwei Beispielen wird gezeigt, wie Ausnahmen, die in einem Thread auftreten,
an den Erzeugerthread propagiert werden:

  * Propagating Exception from `std::async` invocation
  * Propagating Exception from `std::thread` invocation

#### Quellcode:

[Siehe hier](Exception.cpp).

---

[Zurück](../../Readme.md)

---
